import 'dart:io';

import 'package:bwa_fllutix/bloc/blocs.dart';
import 'package:bwa_fllutix/bloc/page_bloc.dart';
import 'package:bwa_fllutix/models/models.dart';
import 'package:bwa_fllutix/services/services.dart';
import 'package:bwa_fllutix/shared/shared.dart';
import 'package:bwa_fllutix/ui/widgets/widgets.dart';
import 'package:email_validator/email_validator.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flushbar/flushbar.dart';
import 'package:flutter/material.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import 'package:provider/provider.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:qr_flutter/qr_flutter.dart';
import 'package:random_string/random_string.dart';
import 'package:bwa_fllutix/extension/extensions.dart';
part'main_page.dart';
part'signIn_page.dart';
part'splash_page.dart';
part 'movie_page.dart';
part'wrapper.dart';
part'account_confirmation_page.dart';
part'preference_page.dart';
part'sign_up_page.dart';
part 'movie_detail_page.dart';
part 'select_schedule_page.dart';
part 'seat_page.dart';
part 'check_out_page.dart';
part 'succes_transaction_page.dart';
part 'ticket_page.dart';
part 'ticket_detail_page.dart';
part 'profile_page.dart';
part 'top_up_page.dart';
part'walet_page.dart';

